name: RC MI2S Inverter
slug: rc_mi2s
version: "1.3.1"
description: Local cloud-free bridge for RC MI2S-800D microinverters to Home Assistant (MQTT discovery)
url: https://github.com/mindulace/rc-mi2s-inverter
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
init: false
services:
  - mqtt:need
options:
  serial: ""
  send_timesync: true
  forward_host: ""
  forward_port: 1883
schema:
  serial: "str?"
  send_timesync: bool
  forward_host: "str?"
  forward_port: port
